
trigger:
- master
- mr/*

pr:
- master

resources:
  repositories:
    - repository: CImakeshift
      type: github
      name: mbeutel/CImakeshift
      endpoint: mbeutel

jobs:
- template: azure-pipelines/cmake.yml@CImakeshift
  parameters:
    vcpkgRef: a9eee3b18df395dbb8be71a31bd78ea441056e42
    vcpkgManifestRoot: '$(Build.SourcesDirectory)/ci'

    cmakeBuildConfigurations: [Debug, RelWithDebInfo]

    targets:

    - os: Windows
      cxxCompiler: MSVC
      cxxCompilerVersions: [VS2022]
      platforms: [x86, x64]
      cmakeConfigPreset: 'ci-msvc'

    - os: Windows
      cxxCompiler: Clang
      cxxCompilerVersions: [VS2022]
      platforms: [x86, x64]
      cmakeConfigPreset: 'ci-clang-cl'

    - os: Linux
      cxxCompiler: GCC
      cxxCompilerVersions: [13, 14]
      platforms: [x64]
      cmakeConfigPreset: 'ci-gcc'

    - os: Linux
      cxxCompiler: Clang
      cxxCompilerVersions: [17, 19]
      platforms: [x64]
      cmakeConfigPreset: 'ci-clang'

    - os: Linux
      cxxCompiler: GCC
      cxxCompilerVersions: [13]
      platforms: [x64]
      tag: 'sanitize'
      cmakeConfigPreset: 'ci-gcc-sanitize'

    - os: Linux
      cxxCompiler: Clang
      cxxCompilerVersions: [19]
      platforms: [x64]
      tag: 'sanitize'
      cmakeConfigPreset: 'ci-clang-sanitize'

    - os: MacOS
      cxxCompiler: GCC
      cxxCompilerVersions: [13, 14]
      platforms: [x64]
      cmakeConfigPreset: 'ci-gcc'

    - os: MacOS
      cxxCompiler: AppleClang
      cxxCompilerVersions: [15_2, 16, 17]
      platforms: [x64]
      cmakeConfigPreset: 'ci-clang'
