
trigger:
- master
- mr/*

pr:
- master

resources:
  repositories:
    - repository: CImakeshift
      type: github
      name: mbeutel/CImakeshift
      endpoint: mbeutel

jobs:
- template: azure-pipelines/cmake.yml@CImakeshift
  parameters:
    vcpkgRef: 07c93b8cd5e2b7fd6d757477d7c59abfc2992842 

    # TODO: this should become unnecessary once Vcpkg knows about makeshift
    postSetupSteps:
    - pwsh: |
        New-Item -Type Directory -Force '$(Agent.BuildDirectory)/makeshift'
        git clone https://github.com/mbeutel/makeshift.git '$(Agent.BuildDirectory)/makeshift'
        New-Item -Type Directory -Force '$(Agent.BuildDirectory)/makeshift/build'
        cd '$(Agent.BuildDirectory)/makeshift/build'
        $vcpkgArgs = $env:CIMAKESHIFT_CMAKE_VCPKG_ARGS_ -split ' '
        & cmake -G $env:CIMAKESHIFT_CMAKE_GENERATOR -DCMAKE_BUILD_TYPE=Debug $(CIMAKESHIFT_CMAKE_CONFIG_ARGS) '$(Agent.BuildDirectory)/makeshift'
      displayName: 'Install makeshift'
    
    cmakeConfigArgs: '-DINTERVALS_BUILD_TESTING=ON -DINTERVALS_BUILD_EXAMPLES=ON -Dmakeshift_DIR=$(Agent.BuildDirectory)/makeshift/build'

    cmakeBuildConfigurations: [Debug, RelWithDebInfo]

    targets:

    - os: Windows
      cxxCompiler: MSVC
      cxxCompilerVersions: [VS2022]
      platforms: [x86, x64]

    - os: Windows
      cxxCompiler: Clang
      cxxCompilerVersions: [VS2022]
      platforms: [x86, x64]

    - os: Linux
      cxxCompiler: GCC
      cxxCompilerVersions: [13]
      platforms: [x64]

    - os: Linux
      cxxCompiler: Clang
      cxxCompilerVersions: [17]
      platforms: [x64]

    - os: Linux
      cxxCompiler: GCC
      cxxCompilerVersions: [13]
      platforms: [x64]
      cxxStandardLibraryDebugMode: true
      cxxSanitizers: [AddressSanitizer, UndefinedBehaviorSanitizer]
      tag: 'sanitize'

    - os: Linux
      cxxCompiler: Clang
      cxxCompilerVersions: [17]
      platforms: [x64]
      cxxStandardLibraryDebugMode: true
      cxxSanitizers: [AddressSanitizer, UndefinedBehaviorSanitizer, ImplicitIntegerArithmeticValueChange]
      tag: 'sanitize'

    - os: MacOS
      cxxCompiler: GCC
      cxxCompilerVersions: [13]
      platforms: [x64]

    - os: MacOS
      cxxCompiler: AppleClang
      cxxCompilerVersions: [15_2]
      platforms: [x64]
